name: Mutation Testing

on:
  push:
    branches: [ "Release/**" ]
  pull_request:
    branches: [ "Release/**" ]
  workflow_dispatch:

jobs:
  mutation-test:
    runs-on: ubuntu-latest

    env:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/Z21.sln
    - name: Build
      run: dotnet build src/Z21.sln --no-restore
    - name: Build target project
      run: dotnet build src/Z21.Client/Z21.Client.csproj -c Debug
      
    - name: Install Stryker.NET
      run: dotnet tool install -g dotnet-stryker

    - name: Run mutation tests
      run: dotnet stryker --reporter dashboard --mutation-level Advanced
